name = "genshin-market-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "genshin-market"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
